const http=require("http");
const fs=require("fs");
const path=require("path");
const crypto=require("crypto");
const {Pool}=require("pg");
const PORT=process.env.PORT||3000,ROOT=__dirname;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
async function setupDatabase(){if(!process.env.DATABASE_URL)return;await pool.query(`CREATE TABLE IF NOT EXISTS comments(id TEXT PRIMARY KEY,post TEXT NOT NULL,name TEXT NOT NULL,comment TEXT NOT NULL,"createdAt" TIMESTAMPTZ NOT NULL,"updatedAt" TIMESTAMPTZ)`);console.log("PostgreSQL database ready")}
function sendJson(res,status,data){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type"});res.end(JSON.stringify(data))}
const responsive=`<style id="futuretech-responsive">*,*::before,*::after{box-sizing:border-box}html,body{width:100%;max-width:100%;overflow-x:hidden}img,video,svg,canvas{max-width:100%;height:auto}iframe{max-width:100%}table{max-width:100%;overflow-x:auto;display:block}pre,code{max-width:100%;overflow-x:auto;white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:900px){header{max-width:100%!important}.intro,.hero,.content,.impact,.team,.contact,.blog,.blog-container{max-width:100%;padding-left:5%!important;padding-right:5%!important}.cards{grid-template-columns:repeat(2,minmax(0,1fr))!important}.intro{gap:30px!important}.container{max-width:100%!important}.timeline-card,.blog-card,.cardi,.impact-box{max-width:100%;min-width:0;overflow-wrap:anywhere}}@media(max-width:650px){header{position:relative!important;height:auto!important;min-height:65px;padding:14px 5%!important;flex-wrap:wrap;gap:12px}nav,header nav{width:100%;max-width:100%}nav ul{justify-content:center!important;flex-wrap:wrap!important;gap:8px 14px!important}.intro{min-height:auto!important;padding-top:70px!important;padding-bottom:55px!important;flex-direction:column!important;text-align:center}.intro h1{font-size:clamp(36px,12vw,60px)!important}.text{font-size:16px!important}.buttons{justify-content:center;flex-wrap:wrap}.r{width:min(100%,300px)!important}.cards{grid-template-columns:1fr!important;gap:18px!important}.card{min-height:auto!important;padding:22px!important}.ai,.impact{padding-top:60px!important;padding-bottom:55px!important}.container{padding-left:10px!important;padding-right:10px!important}.hero img{height:auto!important;min-height:0!important}.hero h1{font-size:clamp(30px,9vw,42px)!important}.content{padding-top:25px!important}.marquee-container{max-width:100%!important}.timeline-card,.blog-card,.cardi,.impact-box{width:100%!important}.containerf h2{font-size:clamp(28px,8vw,40px)!important}}@media(max-width:430px){header>a,.logo{font-size:20px!important}nav ul{gap:6px 9px!important}nav ul li a{font-size:11px!important}.intro h1{font-size:clamp(32px,12vw,48px)!important}.buttons{flex-direction:column;align-items:stretch}.btn{width:100%;text-align:center}.card{padding:18px!important}.cardf{flex-basis:calc(100vw - 40px)!important;width:calc(100vw - 40px)!important}.comments{width:calc(100% - 20px)!important;padding:18px!important}}</style>`;
function sendFile(res,filePath){const types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".ico":"image/x-icon"};fs.readFile(filePath,(e,data)=>{if(e){res.writeHead(e.code==="ENOENT"?404:500);return res.end(e.code==="ENOENT"?"Not found":"Server error")}if(path.extname(filePath).toLowerCase()===".html")data=Buffer.from(data.toString().replace(/<\/head>/i,responsive+"</head>"));res.writeHead(200,{"Content-Type":types[path.extname(filePath).toLowerCase()]||"application/octet-stream"});res.end(data)})}
function body(req){return new Promise((resolve,reject)=>{let d="";req.on("data",c=>{d+=c;if(d.length>10000)req.destroy()});req.on("end",()=>resolve(d));req.on("error",reject)})}
const server=http.createServer(async(req,res)=>{if(req.method==="OPTIONS"){res.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type"});return res.end()}const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);
if(url.pathname==="/api/comments"&&req.method==="GET")try{const post=(url.searchParams.get("post")||"ai").trim();const r=await pool.query('SELECT id,post,name,comment,"createdAt","updatedAt" FROM comments WHERE post=$1 ORDER BY "createdAt" ASC',[post]);return sendJson(res,200,r.rows)}catch(e){console.error(e);return sendJson(res,500,{error:"Database unavailable."})}
if(url.pathname==="/api/comments"&&req.method==="POST")try{const i=JSON.parse(await body(req)),name=String(i.name||"").trim(),text=String(i.comment||"").trim(),post=String(i.post||"ai").trim();if(!name||!text||!post)return sendJson(res,400,{error:"Name, comment and post are required."});if(name.length>50||text.length>1000||post.length>50)return sendJson(res,400,{error:"Input is too long."});const c={id:crypto.randomUUID(),post,name,comment:text,createdAt:new Date().toISOString()};await pool.query('INSERT INTO comments(id,post,name,comment,"createdAt") VALUES($1,$2,$3,$4,$5)',[c.id,c.post,c.name,c.comment,c.createdAt]);return sendJson(res,201,c)}catch(e){console.error(e);return sendJson(res,400,{error:"Invalid request or database error."})}
const m=url.pathname.match(/^\/api\/comments\/([^/]+)$/);if(m&&(req.method==="PUT"||req.method==="DELETE")){const id=decodeURIComponent(m[1]);try{if(req.method==="DELETE"){const r=await pool.query('DELETE FROM comments WHERE id=$1 RETURNING id,post,name,comment,"createdAt","updatedAt"',[id]);if(!r.rows.length)return sendJson(res,404,{error:"Comment not found."});return sendJson(res,200,r.rows[0])}const i=JSON.parse(await body(req)),cur=await pool.query("SELECT name FROM comments WHERE id=$1",[id]);if(!cur.rows.length)return sendJson(res,404,{error:"Comment not found."});const name=String(i.name||cur.rows[0].name).trim(),text=String(i.comment||"").trim();if(!name||!text)return sendJson(res,400,{error:"Name and comment are required."});const u=new Date().toISOString(),r=await pool.query('UPDATE comments SET name=$1,comment=$2,"updatedAt"=$3 WHERE id=$4 RETURNING id,post,name,comment,"createdAt","updatedAt"',[name,text,u,id]);return sendJson(res,200,r.rows[0])}catch(e){console.error(e);return sendJson(res,400,{error:"Invalid request or database error."})}}
if(url.pathname==="/api/health")return sendJson(res,200,{status:"ok"});if(req.method==="GET"){let requested=decodeURIComponent(url.pathname);if(requested==="/")requested="/tech.html";const safe=path.normalize(path.join(ROOT,requested));if(safe.startsWith(ROOT)&&fs.existsSync(safe)&&fs.statSync(safe).isFile())return sendFile(res,safe)}sendJson(res,404,{error:"Not found"})});
setupDatabase().catch(e=>console.error("Database setup failed:",e));server.listen(PORT,()=>console.log(`FutureTechX server running on port ${PORT}`));