-- FutureTechX comments database
-- Run this SQL in Supabase SQL Editor.
-- Also enable Anonymous Sign-Ins in Supabase Authentication settings.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 50),
  text text not null check (char_length(trim(text)) between 1 and 1000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.comments enable row level security;

-- Anyone can read published comments.
drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments
for select
to anon, authenticated
using (true);

-- Only the currently signed-in anonymous/authenticated user can create a comment as themselves.
drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

-- Users can edit only their own comments.
drop policy if exists "Users can edit their own comments" on public.comments;
create policy "Users can edit their own comments"
on public.comments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Users can delete only their own comments.
drop policy if exists "Users can delete their own comments" on public.comments;
create policy "Users can delete their own comments"
on public.comments
for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists comments_created_at_idx
on public.comments (created_at desc);

-- Keep updated_at current.
create or replace function public.set_comments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists comments_updated_at on public.comments;
create trigger comments_updated_at
before update on public.comments
for each row
execute function public.set_comments_updated_at();
