-- FutureTechX comments database
-- Run this SQL in the Supabase SQL Editor.
-- Enable Email authentication in Supabase Authentication settings.

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 50),
  text text not null check (char_length(trim(text)) between 1 and 1000),
  created_at timestamptz not null default now()
);

-- Add post_key safely if an older comments table already exists.
alter table public.comments add column if not exists post_key text;
update public.comments set post_key = 'home' where post_key is null;
alter table public.comments alter column post_key set not null;

alter table public.comments enable row level security;

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments for select
to anon, authenticated
using (true);

drop policy if exists "Users can create their own comments" on public.comments;
create policy "Users can create their own comments"
on public.comments for insert
to authenticated
with check (auth.uid() = user_id);

-- No update policy: comments cannot be edited.
drop policy if exists "Users can edit their own comments" on public.comments;

-- Delete is allowed only when the logged-in user's ID matches the comment owner.
drop policy if exists "Users can delete their own comments" on public.comments;
create policy "Users can delete their own comments"
on public.comments for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists comments_post_created_at_idx
on public.comments (post_key, created_at desc);
